spring:
  application:
    name: gastrotrack-api
  datasource:
    url: jdbc:postgresql://localhost:5433/gastrotrackdb
    username: postgres
    password: password
  sql:
    init:
      mode: always # Ensures schema.sql runs on app startup
  jpa:
    hibernate:
      ddl-auto: none # Prevent Hibernate from auto-creating tables
    show-sql: true # Show SQL queries in logs
    properties:
      hibernate.format_sql: true
    logging:
      level:
        org.hibernate.SQL: DEBUG
        org.hibernate.type.descriptor.sql: TRACE

  security:
    user:
      name: admin
      password: test

  data:
    redis:
      host: redis
      port: 6379

server:
  port: 8085

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html


