spring:
  application:
    name: gastrotrack-api
  datasource:
    url: jdbc:postgresql://your-production-database-url:5432/your-database-name
    username: your-db-username
    password: your-db-password
  jpa:
    hibernate:
      ddl-auto: validate # Use `validate` to ensure schema matches the entity but doesn't modify the database
    show-sql: false # Disable SQL logging in production
    properties:
      hibernate:
        format_sql: false
        dialect: org.hibernate.dialect.PostgreSQLDialect
  data:
    redis:
      host: redis-prod-url
      port: 6379

server:
  port: 8085

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html

jwt:
  secret: your-256-bit-secret-your-256-bit-secret
