spring:
  application:
    name: gastrotrack-api
  profiles:
    active: dev
  datasource:
    url: jdbc:postgresql://localhost:5433/gastrotrackdb
    username: postgres
    password: password
    hikari:
      auto-commit: false
  sql:
    init:
      mode: always # Ensures __schema.sql runs on app startup
  jpa:
    hibernate:
      ddl-auto: update # Automatically update schema based on entities
    show-sql: true # Show SQL queries in logs
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
        type.descriptor.sql.trace: true
    logging:
      level:
        org.hibernate.SQL: DEBUG
        org.hibernate.type.descriptor.sql: TRACE

  security:
    user:
      name: admin
      password: test

server:
  port: 8085

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html

jwt:
  secret: sjqJCYPyDrDWI/flWZDfP2r6hHLDxYHM119NLmVEL2w=

#Actuator
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always

logging:
  level:
    root: info
    org.springframework.security: DEBUG
  file:
    name: /tmp/logs/GastroTrack.log


